name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Service
        run: curl -s https://pytextsummarizer.onrender.com > /dev/null
